language: node_js
node_js:
  - 7.9.0
branches:
  only:
    - master
env:
  global:
    - secure: "eYF2D700/xvM8WSaN8RfgTYraCWTxRZ5CQZSDxy1zh5x4NGH6TODUBUIpoSRZOxU1oy1jM3VDZJo7w5xIpNJAQup3yMHmzaDi7uOe/kkXyReeP0Z9zAztSTocitXkKix9C0CFExFGd2ojI4SzxWxvsVB76OyL0W4Q03OZRB6Vllj3QpmkcZ0xHYoXeJBZWDy44WOOn113ins+Vr40Sm6AZ+yUZD8rWMaeQiBj3q9mqPQaaqeLrQkIWVQRtE6CfWpGlBNYw53HJ8cTOsfrdBsavz+URtfD18hOIAKFDuaTooOb9CKNn1SHn4lBDGhtZROiU2lr7qHC2mLOkKgqtbAuvKLWun0vPIy2uMjQPlT+WRlk/wRfRGMeQujUWutaQpOX8YauvoEVzMtwMV/ZsREgjI0wtNru35TSmvDgtQklAReqCyO9i5kpSS2nXej3lbkwQ7wMFU1wBDbHs1sMHvQ0tuN39Fwvm0XTDzYROeqSivKAZYIUrD3Ft1hm598Nis3p4EptzNfGpNUVVjdO0wXdueknmYsKCowsQX8jGvmqo9mo1/9IunpsLPjB+2OEa60Uy5o7nyCsUnbXBqX/9yycOXUao/0o/9LjtFBbFrtcYfubKeffzsu6XfaO3dT7L7naTovueYugD+kvMOhty2GJzG9fYEuCuBUk1p+tTOVkuk="

script:
  - yarn global add git-credential-env
  - git config credential.helper "env --username=GITHUB_TOKEN"
  - git config user.name "Travis CI"
  - yarn run deploy
